### ISSUE TITLE
Counter Sample Volumes

### ISSUE THREAD

**Issue by aloneguid** [Azure-Samples/service-fabric-mesh#29]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Build and publish **counter** sample from VS 2017, I'd expect clear steps to make this application working, however I can't. Cloning the repo and building the app succeeds, however I'm not quite sure how to get the volume attached to the image.

You've got volume.yaml file in the solution that is supposed to take file share from parameters:

```yaml
volume:
  schemaVersion: 1.0.0-preview1
  name: counterVolume
  properties:
    description: Azure Files storage volume for counter App.
    provider: SFAzureFile
    azureFileParameters: 
        shareName: "[parameters('azurefile-shareName')]"
        accountName: "[parameters('azurefile-accountName')]"
        accountKey: "[parameters('azurefile-accountKey')]"
```

In case we are deploying from VS, where does one provide those parameters? The file share is already deployed, however I should be able to pass the parameters somehow externally? ARM gets generated automatically, however it doesn't mention volume resource at all.

In the **counterService**, service.yaml there are no references to a volume either, so I'm not quite sure where it's supposed to be attached. `FileStoreUtility` is trying to get `STORE_ROOT` from an environment variable, could you please point where it's created?

I'm happy to contribute to the documentation if you can point me in the right direction please.  

### Any log messages given by the failure
no errors.

### OS and Version?
Windows 10

### Versions
Latest SF SDK and Mesh SDK available from WPI. Latest official Docker.

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.
